<a href="https://colab.research.google.com/github/tranquoctruong2503/THUCHANH_DEEPLEARNING/blob/main/ThucHanhBuoi1_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# THUC HANH NUMPY

In [2]:
import numpy as np

In [3]:
#tao mang 1 chieu
print('Cach 1')
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array= np.array(my_list)
print('Numpy array:', my_numpy_array)

print('Cach 2')
a = np.array([1,9,15,39])
print(a)

Cach 1
Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
Cach 2
[ 1  9 15 39]


In [4]:
# tao mang 2 chieu
c = np.array ([(1,2,3),(4,5,6)])
print (c)
print (c.shape)
print (c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [5]:
#tao mang 3 chieu
d = np.array([[[1.,2.,3.],[4.,5.,6.]], [[7.,8.,9.],[10.,11.,12.]]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [6]:
#tao mang gia tri ban dau 0 hoac 1
e= np.zeros((2,2))
f= np.ones((3,3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Em đã tạo được mảng NumPy một chiều, hai chiều và ba chiều bằng Python. Em cũng đã chuyển đổi Python List sang NumPy Array, kiểm tra kích thước mảng bằng shape và xem kiểu dữ liệu bằng dtype. Ngoài ra, tạo được các ma trận chứa toàn số 0 và 1 bằng np.zeros() và np.ones(). Hiểu được cách khởi tạo và thao tác cơ bản với mảng trong thư viện NumPy.

In [7]:
# thay doi kich thuoc Reshape
print('Doi kich thuoc mang 2 chieu')
e = np. array([[1,2,3], [4,5,6]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)

print('Doi kich thuoc mang 3 chieu')
g = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(g)
print(g.shape)
h = g.reshape(3,4)
print(h)

j = g.reshape(3,2,2)
print(j)
k = g.reshape(2,3,2)
print(k)

Doi kich thuoc mang 2 chieu
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
Doi kich thuoc mang 3 chieu
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [8]:
#chuyen mang nhieu chieu thanh 1 chieu Platten
e = np.array([[1,2,3],[4,5,6]])
f = e.flatten()
print(f)

g = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
j= g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


Em đã biết cách thay đổi kích thước mảng bằng reshape() và chuyển mảng nhiều chiều thành mảng một chiều bằng flatten(). Em đã thao tác được với mảng 2 chiều và 3 chiều trong NumPy.

In [9]:
#them dong du lieu hstack và vstack
a = np.array([1,2,3])
b = np.array([4,5,6])
h_stack= np.hstack((a,b))
print('Horizontal\n',h_stack)
v_stack = np.vstack((a,b))
print('Vertical\n',v_stack)

Horizontal
 [1 2 3 4 5 6]
Vertical
 [[1 2 3]
 [4 5 6]]


Em đã biết cách ghép dữ liệu trong NumPy bằng hstack() và vstack() nối mảng theo chiều ngang và chiều dọc để tạo mảng mới từ các mảng ban đầu.

In [10]:
#sinh mang so ngau nhien
#randint la so nguyen
a = np.random.randint(100, size=(5,))
print('Random mang 1 chieu \n', a)

b = np.random.randint(100, size=(3,4))
print('Random mang 2 chieu \n', b)

c = np.random.randint(100, size=(2,3,4))
print('Random mang 3 chieu \n', c)

Random mang 1 chieu 
 [26 54 82 14 99]
Random mang 2 chieu 
 [[68 50 75 14]
 [54 18 19 30]
 [57 11 89 75]]
Random mang 3 chieu 
 [[[ 3 66 52 51]
  [37 76 27 93]
  [85 59 24 67]]

 [[17 81 45 62]
  [91 14 62  2]
  [89 14 23 46]]]


In [11]:
#rand la so thuc
a = np.random.rand(5,)
print('Random mang 1 chieu \n', a)

b = np.random.rand(3,4)
print('Random mang 2 chieu \n', b)

c = np.random.rand(3,4,3)
print('Random mang 3 chieu \n', c)

Random mang 1 chieu 
 [0.61792903 0.62068499 0.19184137 0.80973717 0.1381688 ]
Random mang 2 chieu 
 [[0.10726216 0.43437099 0.37381985 0.53322964]
 [0.81372284 0.53859397 0.47348138 0.76626967]
 [0.07646719 0.49412532 0.73096784 0.94748068]]
Random mang 3 chieu 
 [[[0.6839885  0.5655285  0.43269414]
  [0.67789903 0.375097   0.66920592]
  [0.04265991 0.45320319 0.64929731]
  [0.37706964 0.25630904 0.18479509]]

 [[0.55659489 0.35011302 0.75194657]
  [0.86717604 0.75834462 0.67250452]
  [0.7302374  0.7268417  0.51954607]
  [0.41216306 0.48641018 0.61893736]]

 [[0.3683741  0.21983684 0.51333373]
  [0.47392951 0.09474718 0.72998803]
  [0.81179442 0.4394482  0.32666765]
  [0.27526414 0.30812234 0.74890516]]]


In [12]:
#phan phoi chuan Gaussian
a = np.random.normal(5, 0.5, 10)
print(a)

[5.31996061 5.00290587 5.14293028 5.06393043 5.33510138 5.07098382
 4.57170543 4.64844185 4.55830273 5.15358806]


In [14]:
 #tu mang gia tri cho truoc
print('Sinh 1 gia tri:')
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)

print('Sinh ma tran 3 x 5:')

b = np.random.choice([2,4,6,8,10,12,14,16,18,20], size=(3,5))
print(b)


Sinh 1 gia tri:
20
Sinh ma tran 3 x 5:
[[12 12 10 20 10]
 [ 4  8 18 16 12]
 [12 20 12 10 14]]


Em biết cách phát sinh dữ liệu ngẫu nhiên trong NumPy bằng randint(), rand(), normal() và choice() tạo được mảng ngẫu nhiên 1 chiều, 2 chiều, 3 chiều với số nguyên, số thực, theo phân phối chuẩn Gaussian và lấy giá trị ngẫu nhiên từ một tập dữ liệu cho trước.

In [15]:
# thay doi gia tri cua ma tran
a= np.matrix(np.ones((5,5)))
print('The matrix\n', a)

np.array(a) [2]=2
print('Change values of third row with array\n',a)

np.asarray(a) [2]=2
print('Change values of third row with asarray\n',a)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


Em đã biết cách tạo ma trận bằng np.matrix() và thay đổi giá trị của ma trận thông qua np.array() và np.asarray() tahy đổi giá trị của một hàng trong ma trận NumPy.

In [16]:
# sinh day so theo khoang cho truoc
# arange
a = np.arange(1,20) # tang 1 gia tri
print(a)

b= np.arange(1,20,2) # tang 2 gia tri
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [17]:
#linspace
a= np.linspace(1., 5., num =10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Em đã biết cách sinh dãy số trong NumPy bằng arange() và linspace() dãy số tăng theo bước nhảy xác định và dãy số chia đều trong một khoảng cho trước.

In [18]:
#Index và slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('dong 1:', a[0])
print('dong 2:', a[1])

print('cot 2:', a[:,1])
print('cot 1', a[:, 0])
print('2 gia tri dau dong 2', a[1, :2])

[[1 2 3]
 [4 5 6]]
dong 1: [1 2 3]
dong 2: [4 5 6]
cot 2: [2 5]
cot 1 [1 4]
2 gia tri dau dong 2 [4 5]


Em đã biết cách truy xuất dữ liệu trong mảng NumPy bằng Index và Slice lấy được các hàng, cột và một phần dữ liệu cụ thể trong mảng.

# THUC HANH PANDAS

In [20]:
import pandas as pd

In [21]:
# Series là cấu trúc dữ liệu 1-chiều
a = pd.Series([1.,2.,3.])
print(a)
print('First value:', a[0])

b = pd.Series([1., 2., 3.], index=['a', 'b', 'c'])
print(b)
print('First value:', b['a'])

#Tạo pandas series từ dictionary
calories = {"day1": 420, "day2": 380, "day3": 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value: 1.0
a    1.0
b    2.0
c    3.0
dtype: float64
First value: 1.0
day1    420
day2    380
day3    390
dtype: int64


Em đã biết cách tạo và sử dụng Series trong Pandas từ danh sách, dictionary và biết cách truy xuất dữ liệu bằng chỉ số và nhãn.

In [22]:
#DataFrame là mảng 2-chiều có nhãn ở 2 trục
#Chuyển đổi từ mảng dạng Numpy sang Pandas và ngược lại

h = np.array([[1, 2], [3, 4]])   #Numpy --> Pandas
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

numpy_h = np.array(df_h)         #Pandas --> Numpy
print('Numpy array:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy array:
 [[1 2]
 [3 4]]


In [23]:
#Tạo DataFrame mảng 2-chiều có tên cột
dic = {'Name':['John', 'Smith'], 'Age':[30, 40]}
df_dic = pd.DataFrame(dic)
print(df_dic)

    Name  Age
0   John   30
1  Smith   40


In [24]:
#tạo mảng 20 x 4
r = np.random.randn(20, 4)
df = pd.DataFrame(r, columns=['so1', 'so2', 'so3', 'so4'])
print(df.head())  #in 5 dòng đầu tiên
#chọn 1 cột
print('Chọn cột so1\n',df['so1'])
#chọn nhiều dòng
print('Chọn nhiều dòng\n',df[0:3])
#chọn nhiều cột
print('Chọn nhiều cột\n', df[['so1', 'so3']])
#chọn nhiều dòng, nhiều cột
print('Chọn nhiều dòng, nhiều cột\n', df.iloc[:3, :2])
#Xóa cột
df = df.drop(columns=['so1', 'so4'])
print(df)

        so1       so2       so3       so4
0 -0.494957 -1.493045 -1.188682 -2.012841
1  0.429813  1.070906  0.048131  1.054342
2 -0.272718 -1.040140  0.217777 -0.106697
3  0.764729  1.357178  0.061454  0.242667
4  0.503288  0.124036  0.027377 -1.029759
Chọn cột so1
 0    -0.494957
1     0.429813
2    -0.272718
3     0.764729
4     0.503288
5    -0.476756
6    -1.986300
7    -1.000495
8     2.141243
9     0.205280
10   -1.351337
11   -0.090084
12    0.539845
13    0.524115
14    1.287185
15    1.173866
16   -1.492525
17    1.099589
18    0.744950
19    0.866866
Name: so1, dtype: float64
Chọn nhiều dòng
         so1       so2       so3       so4
0 -0.494957 -1.493045 -1.188682 -2.012841
1  0.429813  1.070906  0.048131  1.054342
2 -0.272718 -1.040140  0.217777 -0.106697
Chọn nhiều cột
          so1       so3
0  -0.494957 -1.188682
1   0.429813  0.048131
2  -0.272718  0.217777
3   0.764729  0.061454
4   0.503288  0.027377
5  -0.476756 -0.867584
6  -1.986300 -1.157038
7  -1.000495 -0.256367


Em đã biết cách tạo và sử dụng DataFrame trong Pandas biết chuyển đổi dữ liệu giữa NumPy và Pandas, tạo DataFrame có tên cột, truy xuất dữ liệu theo dòng và cột, xem các dòng đầu bằng head(), thực hiện xóa cột trong DataFrame.

In [25]:
#Nối 2 DataFrame
df1 = pd.DataFrame({'Name':['John', 'Smith', 'Paul'],
                    'Age':[25, 30, 50]
                   }, index=[0, 1, 2])
df2 = pd.DataFrame({'Name':['Adam', 'Smith'],
                    'Age':[26, 11]
                   }, index=[3, 4])
df_concat = pd.concat([df1, df2])
print('Concate two DataFrame\n', df_concat)
#Xóa những giá trị ở cột Name trùng nhau
print('Drop duplicatevalues in DataFrame\n', df_concat.drop_duplicates('Name'))
#Sắp xếp theo cột
print('Sort values in DataFrame\n',df_concat.sort_values('Age'))
#Đổi tên cột
df_rename = df_concat.rename(columns={'Name':'Surname', 'Age':'Age_pupil'})
print('Rename columns of DataFrame\n', df_rename)

Concate two DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
4  Smith   11
Drop duplicatevalues in DataFrame
     Name  Age
0   John   25
1  Smith   30
2   Paul   50
3   Adam   26
Sort values in DataFrame
     Name  Age
4  Smith   11
0   John   25
3   Adam   26
1  Smith   30
2   Paul   50
Rename columns of DataFrame
   Surname  Age_pupil
0    John         25
1   Smith         30
2    Paul         50
3    Adam         26
4   Smith         11


Em đã biết cách nối hai DataFrame bằng concat(), xóa dữ liệu trùng lặp bằng drop_duplicates(), sắp xếp dữ liệu theo cột bằng sort_values() và đổi tên cột bằng rename() trong Pandas.

In [29]:
#Đọc dữ liệu từ CSV
path = '/content/sample_data/Salary_Data.csv'
COLUMNS = ['YearsExperience', 'Salary']
df_csv = pd.read_csv(path, skipinitialspace=True, names=COLUMNS, index_col=False)
print(df_csv.head())
print(df_csv.shape)
df_csv1 = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv1.head())
print(df_csv1.shape)

   YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0
(30, 2)
   1.1  39343.0
0  1.3  46205.0
1  1.5  37731.0
2  2.0  43525.0
3  2.2  39891.0
4  2.9  56642.0
(29, 2)


Em đã biết cách đọc dữ liệu từ file CSV bằng read_csv() trong Pandas thực hiện được việc đặt tên cột, xem dữ liệu bằng head() và kiểm tra kích thước dữ liệu bằng shape.

In [33]:
#Gom nhóm dữ liệu trong DataFrame
path = '/content/sample_data/Fish.csv'
df_csv = pd.read_csv(path, skipinitialspace=True, index_col=False)
print(df_csv.head())
print(df_csv.groupby(['Species']).mean().head())
print(df_csv.groupby(['Species'])['Weight'].min().head())
print(df_csv.groupby(['Species', 'Height'])['Weight'].min().head())

  Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
             Weight    Length1    Length2    Length3     Height     Width
Species                                                                  
Bream    342.500000  25.150000  27.650000  32.383333  12.370300  4.530200
Parkki   104.909091  16.363636  17.672728  19.645454   7.731213  2.860368
Perch    194.069643  16.617857  18.146428  19.185714   4.986935  2.952862
Pike     459.352941  36.238236  38.891177  41.758823   6.636885  4.228191
Roach     76.025000  16.772500  18.187500  20.585000   5.420998  2.962925
Species
Bream     242.0
Parkki     55.0
Perch       5.9
Pike      200.0
Roach       0.0
Name: Weight, dtype: f

Em đã biết cách gom nhóm dữ liệu trong DataFrame bằng groupby() trong Pandas thực hiện tính giá trị trung bình, giá trị nhỏ nhất theo từng nhóm dữ liệu và gom nhóm theo nhiều cột khác nhau.