<a href="https://colab.research.google.com/github/tranquoctruong2503/THUCHANH_DEEPLEARNING/blob/main/ThucHanhBuoi1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#THUC HANH TENSORFLOW

In [2]:
import tensorflow as tf
import numpy as np

In [3]:
# Tensor 0-chiều
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1= tf.constant(9, tf.int16)
print(r1)

r1_float= tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Congthuong University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Congthuong University', shape=(), dtype=string)


In [5]:
#Tensor 1-chiều
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [6]:
#Tensor 2-chiều
rank_2_tensor= tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [7]:
#Tensor n-chiều
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],[5,6,7,8,9]],
    [[10,11,12,13,14],[15,16,17,18,19]],
    [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [9]:
# Thuoc tinh cuar Tensor
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],[5,6,7,8,9]],
    [[10,11,12,13,14],[15,16,17,18,19]],
    [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)
print('shape:',rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [14]:
# tao tensor tu dong voi gia tri 0 ban dau
# 1 chieu
t_zero = tf.zeros(10)
print(t_zero)

# 2 chieu
t_2_zero = tf.zeros([3,3])
print(t_2_zero)

# 3 chieu
t_3_zero = tf.zeros([3,3,5])
print(t_3_zero)


tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [15]:
# tao tensor tu dong voi gia tri 1 ban dau
# 1 chieu
t_zero = tf.ones(10)
print(t_zero)

# 2 chieu
t_2_zero = tf.ones([3,3])
print(t_2_zero)

# 3 chieu
t_3_zero = tf.ones([3,3,5])
print(t_3_zero)


tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [17]:
#tạo tensor tự động với giá trị bất kỳ
# 1 chieu
t_1 = tf.fill(3,10)
print(t_1)

# 2 chieu
t_2 = tf.fill([3,3], 9)
print(t_2)

# 3 chieu
t_3 = tf.fill([3,3,5], 8)
print(t_3)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]], shape=(3, 3, 5), dtype=int32)


In [19]:
# tạo tensor 1-chiều với hàm linspace trong pham vi
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [22]:
# tạo tensor 1-chiều với hàm range cong them gia tri delta
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor_1 = tf.range(3.0, delta=0.5)
print(range_tensor_1)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [23]:
# tạo tensor với giá trị ngẫu nhiên
# random_normal
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor_1 = tf.random.normal([3,3])
print(range_tensor_1)

range_tensor_2 = tf.random.normal([3,2,2])
print(range_tensor_2)

tf.Tensor([-0.6230215  -0.47171405 -0.18581988 -0.7001924  -1.1991057 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.40566492  0.49102992 -1.2944647 ]
 [ 1.0777715   0.70589703 -0.40062368]
 [-2.1263223  -0.82340515  0.14773302]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[ 0.5222408  -2.0334318 ]
  [ 1.0603825  -0.91993856]]

 [[ 0.42055807  0.45825577]
  [ 0.6320128  -0.39315498]]

 [[ 0.7658212  -0.12319051]
  [-0.5797276  -0.2739836 ]]], shape=(3, 2, 2), dtype=float32)


In [26]:
#random.truncated_normal
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor_1 = tf.random.truncated_normal([3,3])
print(range_tensor_1)

range_tensor_2 = tf.random.truncated_normal([3,2,2])
print(range_tensor_2)
#

tf.Tensor([-0.47988346  0.99758434 -0.32474545  1.027306   -1.319833  ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.8350053   0.37184283 -0.16409083]
 [-0.49520165 -0.5543579  -0.12692471]
 [ 0.8466627  -0.27991903 -0.31540486]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[ 0.9120819  -1.5994179 ]
  [ 0.5205518   1.2221564 ]]

 [[ 0.3484689   0.11918366]
  [-0.13499108 -0.39122382]]

 [[ 1.2386396   1.1669316 ]
  [-1.6390839  -0.03980979]]], shape=(3, 2, 2), dtype=float32)


In [28]:
# random.uniform
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

range_tensor_1 = tf.random.uniform([3,2], minval=10, maxval=20)
print(range_tensor_1)

range_tensor_2 = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor_2)


tf.Tensor([13.030524 16.759495 11.351915 19.15001  11.969345], shape=(5,), dtype=float32)
tf.Tensor(
[[13.82249  15.112367]
 [12.50277  18.238962]
 [16.014225 11.48208 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[14.911842 14.622861 11.846656 16.926998 18.450712]
  [10.174852 19.519543 16.984322 11.890804 10.59423 ]]

 [[12.38591  19.515945 13.871478 17.121658 17.034023]
  [18.739212 19.983248 18.953682 18.09615  10.546171]]

 [[13.427896 16.473675 16.026657 11.693336 11.347477]
  [18.626308 18.44101  15.546837 17.824686 18.685713]]], shape=(3, 2, 5), dtype=float32)


In [29]:
# ngau nhien voi random.uniform vaf shuffle xao tron gia tri
range_tensor= tf.random.uniform([5],minval=10, maxval= 20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([15.646217 12.93527  16.653597 17.907297 16.025833], shape=(5,), dtype=float32)
tf.Tensor([12.93527  16.653597 15.646217 16.025833 17.907297], shape=(5,), dtype=float32)
