<a href="https://colab.research.google.com/github/tranquoctruong2503/THUCHANH_DEEPLEARNING/blob/main/ThucHanhBuoi1_Numpy%26Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# THUC HANH NUMPY

In [2]:
import numpy as np

In [3]:
#tao mang 1 chieu
print('Cach 1')
my_list = [1, 9, 15, 39]
print('Python list:', my_list)
my_numpy_array= np.array(my_list)
print('Numpy array:', my_numpy_array)

print('Cach 2')
a = np.array([1,9,15,39])
print(a)

Cach 1
Python list: [1, 9, 15, 39]
Numpy array: [ 1  9 15 39]
Cach 2
[ 1  9 15 39]


In [4]:
# tao mang 2 chieu
c = np.array ([(1,2,3),(4,5,6)])
print (c)
print (c.shape)
print (c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [6]:
#tao mang 3 chieu
d = np.array([[[1.,2.,3.],[4.,5.,6.]], [[7.,8.,9.],[10.,11.,12.]]])
print(d)
print(d.shape)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)


In [7]:
#tao mang gia tri ban dau 0 hoac 1
e= np.zeros((2,2))
f= np.ones((3,3))
print('Zero matrix:\n', e)
print('One matrix:\n', f)

Zero matrix:
 [[0. 0.]
 [0. 0.]]
One matrix:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [13]:
# thay doi kich thuoc Reshape
print('Doi kich thuoc mang 2 chieu')
e = np. array([[1,2,3], [4,5,6]])
print(e)
print(e.shape)
f = e.reshape(3,2)
print(f)

print('Doi kich thuoc mang 3 chieu')
g = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(g)
print(g.shape)
h = g.reshape(3,4)
print(h)

j = g.reshape(3,2,2)
print(j)
k = g.reshape(2,3,2)
print(k)

Doi kich thuoc mang 2 chieu
[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
Doi kich thuoc mang 3 chieu
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [12]:
#chuyen mang nhieu chieu thanh 1 chieu Platten
e = np.array([[1,2,3],[4,5,6]])
f = e.flatten()
print(f)

g = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
j= g.flatten()
print(j)


[1 2 3 4 5 6]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [15]:
#them dong du lieu hstack và vstack
a = np.array([1,2,3])
b = np.array([4,5,6])
h_stack= np.hstack((a,b))
print('Horizontal\n',h_stack)
v_stack = np.vstack((a,b))
print('Vertical\n',v_stack)

Horizontal
 [1 2 3 4 5 6]
Vertical
 [[1 2 3]
 [4 5 6]]


In [18]:
#sinh mang so ngau nhien
#randint la so nguyen
a = np.random.randint(100, size=(5,))
print('Random mang 1 chieu \n', a)

b = np.random.randint(100, size=(3,4))
print('Random mang 2 chieu \n', b)

c = np.random.randint(100, size=(2,3,4))
print('Random mang 3 chieu \n', c)

Random mang 1 chieu 
 [40 71 33 89 69]
Random mang 2 chieu 
 [[10 97 39 20]
 [75 14 81 62]
 [97 24 53 79]]
Random mang 3 chieu 
 [[[33 38 45 46]
  [42 10 82  2]
  [11 70 99 90]]

 [[13 37 86 39]
  [71 39  0 60]
  [58 40 50 43]]]


In [19]:
#rand la so thuc
a = np.random.rand(5,)
print('Random mang 1 chieu \n', a)

b = np.random.rand(3,4)
print('Random mang 2 chieu \n', b)

c = np.random.rand(3,4,3)
print('Random mang 3 chieu \n', c)

Random mang 1 chieu 
 [0.91614299 0.41211662 0.78081264 0.60716112 0.8904085 ]
Random mang 2 chieu 
 [[0.66978838 0.79167402 0.18644653 0.38639971]
 [0.01745092 0.54397749 0.1676945  0.27594484]
 [0.04626694 0.00164799 0.02195439 0.33143513]]
Random mang 3 chieu 
 [[[0.14885104 0.53816811 0.8187983 ]
  [0.92598106 0.49956337 0.86470114]
  [0.22048102 0.02811649 0.6788364 ]
  [0.668591   0.74577433 0.25495314]]

 [[0.81753591 0.38132872 0.87410982]
  [0.36196508 0.12768024 0.02158984]
  [0.67549698 0.20997245 0.37950229]
  [0.62898741 0.2838734  0.4352341 ]]

 [[0.69681338 0.01471866 0.04025962]
  [0.24631476 0.23157695 0.33708175]
  [0.34686774 0.67522071 0.00788357]
  [0.59740547 0.37141729 0.81488941]]]


In [24]:
#phan phoi chuan Gaussian
a = np.random.normal(5, 0.5, 10)
print(a)

[5.38299781 5.32219281 5.2607342  4.18937263 4.76704069 4.66645456
 5.04340508 4.99486071 5.07316723 5.18881974]


In [28]:
 #tu mang gia tri cho truoc
print('Sinh 1 gia tri:')
a = np.random.choice([2,4,6,8,10,12,14,16,18,20])
print(a)

print('Sinh ma tran 3 x 5:')

b = np.random.choice([2,4,6,8,10,12,14,16,18,20], size=(3,5))
print(b)


Sinh 1 gia tri:
4
Sinh ma tran 3 x 5:
[[ 4 10 20  8  8]
 [18 12  4  8  6]
 [10  8  4  8  8]]


In [29]:
# thay doi gia tri cua ma tran
a= np.matrix(np.ones((5,5)))
print('The matrix\n', a)

np.array(a) [2]=2
print('Change values of third row with array\n',a)

np.asarray(a) [2]=2
print('Change values of third row with asarray\n',a)

The matrix
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Change values of third row with asarray
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
# sinh day so theo khoang cho truoc
# arange
a = np.arange(1,20) # tang 1 gia tri
print(a)

b= np.arange(1,20,2) # tang 2 gia tri
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [36]:
#linspace
a= np.linspace(1., 5., num =10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [41]:
#Index và slice
a = np.array([(1, 2, 3), (4, 5, 6)])
print(a)
print('dong 1:', a[0])
print('dong 2:', a[1])

print('cot 2:', a[:,1])
print('cot 1', a[:, 0])
print('2 gia tri dau dong 2', a[1, :2])

[[1 2 3]
 [4 5 6]]
dong 1: [1 2 3]
dong 2: [4 5 6]
cot 2: [2 5]
cot 1 [1 4]
2 gia tri dau dong 2 [4 5]


# THUC HANH PANDAS

In [43]:
import pandas as pd

In [45]:
# Series là cấu trúc dữ liệu 1-chiều
a = pd.Series([1.,2.,3.])
print(a)
print('Gia tri dau:', a[0])

0    1.0
1    2.0
2    3.0
dtype: float64
Gia tri dau: 1.0
