<a href="https://colab.research.google.com/github/tranquoctruong2503/THUCHANH_DEEPLEARNING/blob/main/ThucHanhBuoi1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#THUC HANH TENSORFLOW

In [31]:
import tensorflow as tf
import numpy as np

In [32]:
# Tensor 0-chiều
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


In [33]:
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1= tf.constant(9, tf.int16)
print(r1)

r1_float= tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Congthuong University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Congthuong University', shape=(), dtype=string)


In [34]:
#Tensor 1-chiều
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [35]:
#Tensor 2-chiều
rank_2_tensor= tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [36]:
#Tensor n-chiều
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],[5,6,7,8,9]],
    [[10,11,12,13,14],[15,16,17,18,19]],
    [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [37]:
# Thuoc tinh cuar Tensor
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],[5,6,7,8,9]],
    [[10,11,12,13,14],[15,16,17,18,19]],
    [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)
print('shape:',rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


In [38]:
# tao tensor tu dong voi gia tri 0 ban dau
# 1 chieu
t_zero = tf.zeros(10)
print(t_zero)

# 2 chieu
t_2_zero = tf.zeros([3,3])
print(t_2_zero)

# 3 chieu
t_3_zero = tf.zeros([3,3,5])
print(t_3_zero)


tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [39]:
# tao tensor tu dong voi gia tri 1 ban dau
# 1 chieu
t_zero = tf.ones(10)
print(t_zero)

# 2 chieu
t_2_zero = tf.ones([3,3])
print(t_2_zero)

# 3 chieu
t_3_zero = tf.ones([3,3,5])
print(t_3_zero)


tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


In [40]:
#tạo tensor tự động với giá trị bất kỳ
# 1 chieu
t_1 = tf.fill(3,10)
print(t_1)

# 2 chieu
t_2 = tf.fill([3,3], 9)
print(t_2)

# 3 chieu
t_3 = tf.fill([3,3,5], 8)
print(t_3)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]], shape=(3, 3, 5), dtype=int32)


In [41]:
# tạo tensor 1-chiều với hàm linspace trong pham vi
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [42]:
# tạo tensor 1-chiều với hàm range cong them gia tri delta
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor_1 = tf.range(3.0, delta=0.5)
print(range_tensor_1)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


In [43]:
# tạo tensor với giá trị ngẫu nhiên
# random_normal
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor_1 = tf.random.normal([3,3])
print(range_tensor_1)

range_tensor_2 = tf.random.normal([3,2,2])
print(range_tensor_2)

tf.Tensor([-1.1495785   1.3257048  -0.26646158  0.5042335  -0.7585718 ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.41354957  0.11326725 -0.28327972]
 [-1.3122069   0.8142849   1.3417454 ]
 [-1.2142675   0.9727173  -0.34625202]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[-1.4709190e+00  9.4415265e-01]
  [-1.2835681e-03  2.5139207e-01]]

 [[ 1.3750722e+00 -1.9235636e-01]
  [-1.1462748e+00  1.4686500e+00]]

 [[-1.5971853e-01  1.0598024e+00]
  [ 1.3844016e+00 -3.1596744e-01]]], shape=(3, 2, 2), dtype=float32)


In [44]:
#random.truncated_normal
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor_1 = tf.random.truncated_normal([3,3])
print(range_tensor_1)

range_tensor_2 = tf.random.truncated_normal([3,2,2])
print(range_tensor_2)
#

tf.Tensor([-0.2538449   0.32608968 -0.45328656  1.6671616   1.26022   ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 1.4614693  1.7271545  0.5882308]
 [-1.1252733  1.2770004 -1.0866358]
 [-0.3755676 -0.9145278 -1.6343106]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[ 0.7854849   0.20375517]
  [ 1.3858768  -0.34992757]]

 [[ 0.258903   -0.0869396 ]
  [ 0.05405649  1.320553  ]]

 [[ 1.1721798  -0.2845004 ]
  [ 0.14666267 -0.7404586 ]]], shape=(3, 2, 2), dtype=float32)


In [45]:
# random.uniform
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

range_tensor_1 = tf.random.uniform([3,2], minval=10, maxval=20)
print(range_tensor_1)

range_tensor_2 = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor_2)


tf.Tensor([10.603907 15.879889 14.551783 13.943738 16.399479], shape=(5,), dtype=float32)
tf.Tensor(
[[13.292333 13.255537]
 [19.09336  16.853582]
 [18.43163  13.730862]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[10.203295 11.298112 16.30967  12.307662 12.350849]
  [12.494306 19.50195  12.171583 12.429858 14.834882]]

 [[13.087452 10.552183 17.848948 12.78488  13.343019]
  [17.15142  12.14176  10.0958   18.134945 19.05073 ]]

 [[15.794933 18.906628 16.746044 17.763245 12.928333]
  [11.974706 16.987686 16.689444 17.03679  15.807005]]], shape=(3, 2, 5), dtype=float32)


In [46]:
# ngau nhien voi random.uniform vaf shuffle xao tron gia tri
range_tensor= tf.random.uniform([5],minval=10, maxval= 20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([14.360495 11.717461 15.112139 10.357455 19.972824], shape=(5,), dtype=float32)
tf.Tensor([19.972824 11.717461 14.360495 10.357455 15.112139], shape=(5,), dtype=float32)


In [47]:
# chuyen doi kieu du lieu
t_float = tf.constant(3.9, tf.float32)
print(t_float,'---', t_float.dtype)

t_int = tf.cast(t_float,dtype=tf.int32)
print(t_int,'---',t_int.dtype)


tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


In [48]:
# cac phep toan
# tinh can bac 2
x = tf.constant(2,ty)

NameError: name 'ty' is not defined