<a href="https://colab.research.google.com/github/tranquoctruong2503/THUCHANH_DEEPLEARNING/blob/main/ThucHanhBuoi1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#THUC HANH TENSORFLOW

In [1]:
import tensorflow as tf
import numpy as np


In [2]:
# Tensor 0-chiều
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

r1= tf.constant(9, tf.int16)
print(r1)

r1_float= tf.constant(1.12, tf.float32)
print(r1_float)

r1_string = tf.constant('Hello Congthuong University', tf.string)
print(r1_string)

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int16)
tf.Tensor(1.12, shape=(), dtype=float32)
tf.Tensor(b'Hello Congthuong University', shape=(), dtype=string)


In [3]:
#Tensor 1-chiều
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [4]:
#Tensor 2-chiều
rank_2_tensor= tf.constant([[1,2],[3,4],[5,6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


In [5]:
#Tensor n-chiều
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],[5,6,7,8,9]],
    [[10,11,12,13,14],[15,16,17,18,19]],
    [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


Em đã biết cách tạo các Tensor trong TensorFlow từ 0 chiều, 1 chiều, 2 chiều đến nhiều chiều thực hiện khai báo Tensor với nhiều kiểu dữ liệu : số nguyên, số thực, chuỗi, biểu diễn dữ liệu đa chiều trong TensorFlow.

In [6]:
# Thuoc tinh cua Tensor
rank_3_tensor = tf.constant([
    [[0,1,2,3,4],[5,6,7,8,9]],
    [[10,11,12,13,14],[15,16,17,18,19]],
    [[20,21,22,23,24],[25,26,27,28,29]],
])
print(rank_3_tensor)
print('shape:',rank_3_tensor.shape)
print('type of tensor:',rank_3_tensor.dtype)


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
shape: (3, 2, 5)
type of tensor: <dtype: 'int32'>


Em biết cách xem các thuộc tính của Tensor trong TensorFlow kích thước bằng shape và kiểu dữ liệu bằng dtype.

In [7]:
# tao tensor tu dong voi gia tri 0 ban dau
# 1 chieu
t_zero = tf.zeros(10)
print(t_zero)

# 2 chieu
t_2_zero = tf.zeros([3,3])
print(t_2_zero)

# 3 chieu
t_3_zero = tf.zeros([3,3,5])
print(t_3_zero)


tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 3, 5), dtype=float32)


In [8]:
# tao tensor tu dong voi gia tri 1 ban dau
# 1 chieu
t_zero = tf.ones(10)
print(t_zero)

# 2 chieu
t_2_zero = tf.ones([3,3])
print(t_2_zero)

# 3 chieu
t_3_zero = tf.ones([3,3,5])
print(t_3_zero)


tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]], shape=(3, 3, 5), dtype=float32)


Em biết cách tạo Tensor tự động với giá trị khởi tạo là 0 bằng tf.zeros() và giá trị 1 bằng tf.ones() trên 1 chiều, 2 chiều và 3 chiều

In [9]:
#tạo tensor tự động với giá trị bất kỳ
# 1 chieu
t_1 = tf.fill(3,10)
print(t_1)

# 2 chieu
t_2 = tf.fill([3,3], 9)
print(t_2)

# 3 chieu
t_3 = tf.fill([3,3,5], 8)
print(t_3)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor(
[[9 9 9]
 [9 9 9]
 [9 9 9]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]

 [[8 8 8 8 8]
  [8 8 8 8 8]
  [8 8 8 8 8]]], shape=(3, 3, 5), dtype=int32)


In [10]:
# tạo tensor 1-chiều với hàm linspace trong pham vi
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)


In [11]:
# tạo tensor 1-chiều với hàm range cong them gia tri delta
range_tensor = tf.range(3.0, 7.0, delta=0.5)
print(range_tensor)

range_tensor_1 = tf.range(3.0, delta=0.5)
print(range_tensor_1)

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0.  0.5 1.  1.5 2.  2.5], shape=(6,), dtype=float32)


Em đã biết cách tạo Tensor với giá trị bất kỳ bằng tf.fill(), tạo dãy giá trị bằng tf.linspace() và tf.range() trên 1 chiều, 2 chiều và 3 chiều với các giá trị mong muốn.

In [12]:
# tạo tensor với giá trị ngẫu nhiên
# random_normal
range_tensor = tf.random.normal([5])
print(range_tensor)

range_tensor_1 = tf.random.normal([3,3])
print(range_tensor_1)

range_tensor_2 = tf.random.normal([3,2,2])
print(range_tensor_2)

tf.Tensor([ 0.30810598 -0.11661745  1.0901822  -1.9121916  -0.60272825], shape=(5,), dtype=float32)
tf.Tensor(
[[ 0.03414018 -0.5947705  -0.13418496]
 [-0.03943896  0.3813069  -0.9486869 ]
 [-1.1503905   2.7104597  -0.81137455]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[ 0.4152568  -0.45392817]
  [ 0.5696234   0.18742225]]

 [[-0.66785276  0.35297987]
  [-1.0716213   1.5101485 ]]

 [[-0.5936704  -1.1497548 ]
  [-0.42938322  0.08997102]]], shape=(3, 2, 2), dtype=float32)


In [13]:
#random.truncated_normal
range_tensor = tf.random.truncated_normal([5])
print(range_tensor)

range_tensor_1 = tf.random.truncated_normal([3,3])
print(range_tensor_1)

range_tensor_2 = tf.random.truncated_normal([3,2,2])
print(range_tensor_2)
#

tf.Tensor([-0.3107144   1.4528074  -0.7882668  -0.57121956 -0.527657  ], shape=(5,), dtype=float32)
tf.Tensor(
[[ 1.140491    0.55002064 -1.2941623 ]
 [-0.506084    0.04335251 -0.20912589]
 [-0.4384395   1.6800046  -1.0606793 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[-0.40409443 -1.6128042 ]
  [ 1.4204159   0.43204522]]

 [[-0.07259443  0.19577764]
  [-0.74116117  0.4008226 ]]

 [[ 1.1443037   0.44180354]
  [ 1.2700236   0.6173515 ]]], shape=(3, 2, 2), dtype=float32)


In [14]:
# random.uniform
range_tensor = tf.random.uniform([5], minval=10, maxval=20)
print(range_tensor)

range_tensor_1 = tf.random.uniform([3,2], minval=10, maxval=20)
print(range_tensor_1)

range_tensor_2 = tf.random.uniform([3,2,5], minval=10, maxval=20)
print(range_tensor_2)


tf.Tensor([15.959177 16.964073 14.371857 18.56803  10.596074], shape=(5,), dtype=float32)
tf.Tensor(
[[16.884197 14.195183]
 [12.423185 17.063892]
 [16.963242 15.111059]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[[17.298086 13.733701 19.470997 17.610409 13.680641]
  [19.749699 10.69315  15.617987 19.576283 13.18987 ]]

 [[10.54545  13.55427  13.072852 10.436649 12.609786]
  [16.713839 18.039055 13.908018 15.925521 11.209522]]

 [[19.437464 13.9608   19.208687 11.450091 17.741234]
  [12.13781  13.473974 19.546003 13.853853 15.737649]]], shape=(3, 2, 5), dtype=float32)


In [15]:
# ngau nhien voi random.uniform vaf shuffle xao tron gia tri
range_tensor= tf.random.uniform([5],minval=10, maxval= 20)
print(range_tensor)
print(tf.random.shuffle(range_tensor))

tf.Tensor([16.45006  14.036485 16.102795 11.094519 16.87807 ], shape=(5,), dtype=float32)
tf.Tensor([14.036485 16.102795 16.87807  11.094519 16.45006 ], shape=(5,), dtype=float32)


In [16]:
# chuyen doi kieu du lieu
t_float = tf.constant(3.9, tf.float32)
print(t_float,'---', t_float.dtype)

t_int = tf.cast(t_float,dtype=tf.int32)
print(t_int,'---',t_int.dtype)


tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int32) --- <dtype: 'int32'>


In [17]:
# cac phep toan
print('Tinh can bac 2')
x = tf.constant(2,dtype=tf.float32)
print(tf.sqrt(x))

print('Cong 2 tensor')
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)
c = tf.add(a,b)
d = a+b
print(c)
print(d)

print('Nhan 2 tensor')
a = tf.constant([[1,2]], tf.int32)
b = tf.constant([[3,4]], tf.int32)
c = tf.multiply(a,b)
d = a*b
print(c)
print(d)


Tinh can bac 2
tf.Tensor(1.4142135, shape=(), dtype=float32)
Cong 2 tensor
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
tf.Tensor([[4 6]], shape=(1, 2), dtype=int32)
Nhan 2 tensor
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)
tf.Tensor([[3 8]], shape=(1, 2), dtype=int32)


In [18]:
# cac ham tinh toan
a = tf.constant([6. , 6. , 6.])
b = tf.constant([4. , 4. , 4.])
c = tf.constant([3. , 3. , 3.])
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print(d)
print(e)
print(f)
print(g)
print(h)
print(i)
print(j)
print(k)
print(l)

tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)
tf.Tensor([13. 13. 13.], shape=(3,), dtype=float32)
tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
tf.Tensor([24. 24. 24.], shape=(3,), dtype=float32)
tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float32)
tf.Tensor([18. 18. 18.], shape=(3,), dtype=float32)
tf.Tensor([0.16666667 0.16666667 0.16666667], shape=(3,), dtype=float32)
tf.Tensor([2. 2. 2.], shape=(3,), dtype=float32)
tf.Tensor([-6. -6. -6.], shape=(3,), dtype=float32)


In [19]:
# các phép toán làm tròn và so sánh
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print(r1)
print(r2)
print(r3)
print(r4)

tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


In [20]:
# các phép toàn trên vector và ma trận
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                  [4, 5, 6]])
t4 = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])
dot_x = tf.tensordot(t1, t2, 0)
dot_y = tf.tensordot(t1, t2, 1)
print(t1)
print(t2)
print(t3)
print(t4)
cross = tf.linalg.cross(t1, t2)
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5, 5)
print(dot_x)
print(d)
print(cross)
print(trace)
print(trans)
print(eye)

tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


In [21]:
# Khai báo một biến trong tensorflow
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
print('Shape', diem.shape)
print('Dtype', diem.dtype)
print('numpy:', diem.numpy())

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
Shape (2,)
Dtype <dtype: 'int32'>
numpy: [5 9]


In [22]:
# Phép gán
toan = tf.Variable(8.5, dtype=tf.float32)
print(toan)
diem = tf.Variable([5, 9])
print(diem)
diem.assign([8, 10])
print(diem)
diem.assign_add([1, 1])
print(diem)
diem.assign_sub([5, 5])
print(diem)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=8.5>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([5, 9], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 8, 10], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 11], dtype=int32)>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([4, 6], dtype=int32)>


In [23]:
# Graph trong tensorflow
# Define a Python function.
def a_regular_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# `a_function_that_uses_a_graph` is a TensorFlow `Function`.
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors.
x1 = tf.constant([[1.0, 2.0]])
y1 = tf.constant([[2.0], [3.0]])
b1 = tf.constant(4.0)

orig_value = a_regular_function(x1, y1, b1).numpy()
# Call a `Function` like a Python function.
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


In [24]:
# Dùng decorator để biến một hàm Python thành graph
def inner_function(x, y, b):
    x = tf.matmul(x, y)
    x = x + b
    return x

# Use the decorator to make `outer_function` a `Function`.
@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)

    return inner_function(x, y, b)

# Note that the callable will create a graph that
# includes `inner_function` as well as `outer_function`.
rs = outer_function(tf.constant([[1.0, 2.0]])).numpy()
print(rs)

[[12.]]


In [25]:
# Modules, Layers và Models
# Tạo lớp SimpleModule xử lý tensor scalar (Layer)
class SimpleModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)
        self.a_variable = tf.Variable(5.0, name="train_me")
        self.non_trainable_variable = tf.Variable(5.0, trainable=False, name="do_not_train_me")

    def __call__(self, x):
        return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")

rs = simple_module(tf.constant(5.0))
print(rs)
print('Train variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Train variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


In [26]:
# Tạo model với nhiều tầng (layer).
class Dense(tf.Module):
    def __init__(self, in_features, out_features, name=None):
        super().__init__(name=name)
        self.w = tf.Variable(
            tf.random.normal([in_features, out_features]), name='w')
        self.b = tf.Variable(tf.zeros([out_features]), name='b')
    def __call__(self, x):
        y = tf.matmul(x, self.w) + self.b
        return tf.nn.relu(y)

class SequentialModule(tf.Module):
    def __init__(self, name=None):
        super().__init__(name=name)

        self.dense_1 = Dense(in_features=3, out_features=3)
        self.dense_2 = Dense(in_features=3, out_features=2)

    def __call__(self, x):
        x = self.dense_1(x)
        return self.dense_2(x)

# You have made a model!
my_model = SequentialModule(name="the_model")

# Call it, with random results
print("Model results:", my_model(tf.constant([[2.0, 2.0, 2.0]])))

Model results: tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


In [27]:
# Lưu weight
# Lưu checkpoint
chkp_path = "my_checkpoint"
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

'my_checkpoint'

In [28]:
# Phục hồi checkpoint
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore("my_checkpoint")

print(new_model(tf.constant([[2.0, 2.0, 2.0]])))

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
